# Generated by Django 2.2 on 2020-06-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя категории')),
                ('discription', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
        ),
    ]
