# Generated by Django 2.2 on 2020-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Описание категорий'),
        ),
    ]
