# Generated by Django 2.2 on 2020-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
